ep3/config/routes.rb
Rails.application.routes.draw do
  	resources :services do
  		member do
  			put 'like' => 'services#like'
  			put 'dislike' => 'services#dislike'

  		end
  		get '/services/:id/like' => 'services#like'

  	end
    get '/my' => 'services#my_services'  
    post '/services/compra' => 'services#comprar_servico'
  	resources :categories
  	devise_for :users
    post '/services/:id/edit' => 'services#edit'

    devise_scope :user do  
	     get '/users/sign_out' => 'devise/sessions#destroy'     
	  end
    root 'home#index'
end

ep3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ep3/app/models/category.rb
class Category < ApplicationRecord
	paginates_per 10
	has_many :services
end

ep3/app/models/service.rb
class Service < ApplicationRecord
	
	paginates_per 10
  	belongs_to :user
  	belongs_to :category
  	acts_as_votable
end

ep3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_voter
  has_many :services
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

ep3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :sobrenome)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :sobrenome)}
          end
end

ep3/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:titulo).page params[:page]
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @services = Service.where(category_id: @category.id).order(:titulo).page params[:page]
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:titulo)
    end
end

ep3/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

ep3/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :sobrenome
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :sobrenome
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :sobrenome)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :sobrenome)
  end
end

ep3/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :like, :dislike]
  before_action :authenticate_user!


  # GET /services
  # GET /services.json
  def index
    @services = Service.order(:titulo).page params[:page]
  end

  def my_services
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  def comprar_servico
    flash[:notice] = "Compra realizada com sucesso!"
    redirect_to services_path
  end


  def like
    if !current_user.voted_up_on? @service
      @service.liked_by current_user
    elsif current_user.voted_up_on? @service
      @service.unliked_by current_user
    end
    if current_user.voted_down_on? @service
      @service.undisliked_by current_user        
    end
    redirect_to @service
  end

  def dislike
    if !current_user.voted_down_on? @service
      @service.downvote_from current_user
    elsif current_user.voted_down_on? @service
      @service.undisliked_by current_user
    end
    if current_user.voted_up_on? @service
      @service.unliked_by current_user 
    end
    redirect_to @service
  end
  # GET /services/new
  def new
    @service = Service.new
    @categories = Category.all
  end

  # GET /services/1/edit
  def edit
    @categories = Category.all
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @categories = Category.all
    @service.category_id = params[:category_id]
    @service.user_id = current_user.id
    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    @service.category_id = params[:category_id]
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Serviço atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Serviço deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:titulo, :descricao, :user_id, :category_id, :preco, :horario)
    end
end

ep3/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    messages = ""
    [:notice, :info, :warning, :error].each {|type|
      if flash[type]
        messages += "<p class=\"#{type}\">#{flash[type]}</p>"
      end
    }

    messages
  end
end

ep3/app/helpers/categories_helper.rb
module CategoriesHelper
end

ep3/app/helpers/home_helper.rb
module HomeHelper
end

ep3/app/helpers/services_helper.rb
module ServicesHelper
end

ep3/app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>

  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:titulo) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

ep3/app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%='Categorias' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= 'Quantidade de Serviços' %></th>
      <th><%=t '.ações', :default => t("helpers.ações") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%=category.titulo%></td>
        <td><%=Service.where(category_id: category.id).length %></td>
        <td>
          <%= link_to t('.ver_serviços', :default => t("helpers.links.ver_serviços")),
                      category_path(category), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @categories, window: 2 %>

ep3/app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=@category.titulo %></h1>
  <hr>
  <h3><%= 'Serviços' %></h3>

<table class="table table-striped">
    <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      
      <th><%= model_class.human_attribute_name(:proprietário_id) %></th>
      <th><%= model_class.human_attribute_name(:likes) %></th>
      <th><%= model_class.human_attribute_name(:dislikes) %></th>
      <th><%= model_class.human_attribute_name(:preco) %></th>
      <th><%= model_class.human_attribute_name(:horario) %></th>
      
      <th><%=t '.ações', :default => t("helpers.ações") %></th>
    </tr>
</thead>
  <tbody>
  <%@services.each do |service|%>
  	<tr>
        
        <td><%= service.titulo %></td>
      
        <td><%= User.find(service.user_id).name %> <%=User.find(service.user_id).sobrenome%></td>
        <td><%= service.get_likes.size %></td>
        <td><%= service.get_dislikes.size %></td>
        <td><%= service.preco %></td>
        <td><%= service.horario %></td>
        <td>
          <%= link_to t('.ver_serviço', :default => t("helpers.links.ver_serviço")),
                      service_path(service), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
  <%end%>
</tbody>
</table>
</div>
<%= link_to 'Voltar', categories_path, :class => 'btn btn-default'  %>
<%= paginate @services, window: 2%> 

ep3/app/views/home/index.html.erb
<h2> Bem Vindo(a) ao I-Need! </h2>
<p> O I-Need é um site que te ajuda a encontrar serviços que você pode precisar mas não sabe onde procura, ao mesmo tempo, é um lugar aonde você ppode ofereçer serviços para poder tirar um sustento disso! Faça seu cadastro e participe já!</p>

ep3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "I-Need" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">I-Need</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <p class="navbar-text pull-right">
              <% if user_signed_in? %>
                Logado como: <strong><%= current_user.name %> <%= current_user.sobrenome%></strong>.
                <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method:  :delete, :class => 'navbar-link'  %> |
              <% else %>
                <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
              <% end %> 
              <%= link_to "Página Inicial", root_path, :class => 'navbar-link' %>
         </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Opções</h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Ofertar Serviço", new_service_path  %></li>
              <li><%= link_to "Serviços disponíveis", services_path   %></li>
              <li><%= link_to "Ver Categorias", categories_path   %></li>
              <li><%= link_to "Meu(s) Serviços",  my_path, :class => 'navbar-link' %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

ep3/app/views/services/_form.html.erb
<%= form_for @service, :html => { :class => "form-horizontal service" } do |f| %>

  <% if @service.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @service.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:titulo) %>
  </div>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>
  
  <div class="form-group">
    <%= f.label 'Preço (Reais)', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :preco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:preco) %>
  </div>
  <div class="form-group">
    <%= f.label :horario, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :horario, :class => 'form-control' %>
    </div>
    <%=f.error_span(:horario) %>
  </div>
  <div class="form-group">
    <%= f.label :categoria_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select_tag :category_id, options_from_collection_for_select(@categories, "id", "titulo"), prompt: "Selecione uma categoria"%>
    </div>
    <%=f.error_span(:category_id) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Criar Serviço', :class => 'btn btn-primary' %>
      <%= link_to t('.cancelar', :default => t("helpers.links.cancelar")),
                services_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

ep3/app/views/services/edit.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

ep3/app/views/services/index.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%='Serviços' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      
      <th><%= model_class.human_attribute_name(:proprietário_id) %></th>
      <th><%= model_class.human_attribute_name(:categoria_id) %></th>
      <th><%= model_class.human_attribute_name(:likes) %></th>
      <th><%= model_class.human_attribute_name(:dislikes) %></th>
      <th><%= 'Preço' %></th>
      <th><%= model_class.human_attribute_name(:horario) %></th>
      
      <th><%=t '.ações', :default => t("helpers.ações") %></th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        
        <td><%= service.titulo %></td>
      
        <td><%= User.find(service.user_id).name %> <%=User.find(service.user_id).sobrenome%></td>
        <td><%= link_to Category.find(service.category_id).titulo , category_path(service.category_id) %></td>
        <td><%= service.get_likes.size %></td>
        <td><%= service.get_dislikes.size %></td>
        <td><%= service.preco %> R$</td>
        <td><%= service.horario %></td>
        <td>
          <%= link_to t('.ver_serviço', :default => t("helpers.links.ver_serviço")),
                      service_path(service), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @services, window: 2 %>

ep3/app/views/services/my_services.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%='Meu(s) Serviços' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      
      
      <th><%= model_class.human_attribute_name(:categoria_id) %></th>
      
      
      <th><%=t '.ações', :default => t("helpers.ações") %></th>
    </tr>
  </thead>
  <tbody>
    <% Service.where(user_id: current_user.id).each do |service| %>
      <tr>
        
        <td><%= service.titulo %></td>
      
        <td><%= link_to Category.find(service.category_id).titulo , category_path(service.user_id) %></td>
        <td>
          <%= link_to t('.ver_serviço', :default => t("helpers.links.ver_serviço")),
                      service_path(service), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

ep3/app/views/services/new.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%='Novo Serviço' %></h1>
</div>
<%= render :partial => 'form' %>

ep3/app/views/services/show.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%='Serviço' %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @service.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @service.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:proprietario) %>:</strong></dt>
  <dd><%= User.find(@service.user_id).name %> <%=User.find(@service.user_id).sobrenome%></dd>
  <dt><strong><%= model_class.human_attribute_name(:categoria) %>:</strong></dt>
  <dd><%= link_to Category.find(@service.category_id).titulo , category_path(@service.category_id)  %></dd>
  <dt><strong><%= model_class.human_attribute_name(:likes) %>:</strong></dt>
  <dd><%= @service.get_upvotes.size%></dd>
  <dt><strong><%= model_class.human_attribute_name(:deslikes) %>:</strong></dt>
  <dd><%= @service.get_downvotes.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:preco) %>:</strong></dt>
  <dd><%= @service.preco%><%= ' R$'%></dd>
  <dt><strong><%= model_class.human_attribute_name(:horario) %>:</strong></dt>
  <dd><%= @service.horario %></dd>
</dl>
<%if current_user.id == @service.user_id%>
  <%= button_to('Editar',edit_service_path(@service),method: :get,:class => 'btn btn-default btn-like', remote: :true) %>
  <%= button_to('Deletar',service_path(@service), method: :delete,:class => 'btn btn-danger btn-dislike', remote: :true) %>
  <br />
<%else%>
  <%= button_to('Like',like_service_path(@service), method: :put,:class => 'btn btn-default btn-like', remote: :true) %>
  <%= button_to('Dislike',dislike_service_path(@service), method: :put,:class => 'btn btn-default btn-dislike', remote: :true) %>
  <%= button_to('Comprar', services_compra_path(@service.id), method: :post,:class => 'btn btn-default btn-buy') %>
<%end%>



<hr>

<%= link_to t('.voltar', :default => t("helpers.links.voltar")),
              services_path, :class => 'btn btn-default btn-back'  %>



<style type="text/css">
  .btn-like {
    float:left;
    margin-right: 5px
  }
  .btn-dislike {
   float:left;
   margin-left: 5px
  }
  .btn-back{
    float: :left;
    margin-right: 5px
    margin-top: 5px;
  }

  .btn-buy{
    float: :left;
    margin-left: 10px
  }
</style>

ep3/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

ep3/app/views/users/shared/_links.html.erb
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>